def get_merge_query_marketing_campaigns_union() -> str:
    return """
MERGE INTO ODS.MARKETING_CAMPAIGNS AS ODS
USING (
    -- ASIA
    SELECT
        campaign_id,
        campaign_name,
        campaign_type,
        channel,
        start_date,
        end_date,
        CAST(budget_usd AS DECIMAL(10,2)) AS budget_usd,
        target_audience,
        campaign_status,
        NULL AS is_gdpr_compliant,
        CAST(created_at AS TIMESTAMP) AS created_at,
        created_at AS updated_at,
        'ASIA' AS source_region,
        _source AS source_system
    FROM staging_asia.marketing_campaigns

    UNION ALL

    -- EU
    SELECT
        CAMPAIGN_ID,
        CAMPAIGN_NAME,
        CAMPAIGN_TYPE,
        CHANNEL,
        START_DATE,
        END_DATE,
        CAST(BUDGET_USD AS DECIMAL(10,2)) AS BUDGET_USD, 
        TARGET_AUDIENCE,
        CAMPAIGN_STATUS,
        GDPR_COMPLIANT AS IS_GDPR_COMPLIANT,
        CREATED_AT,
        created_at AS updated_at,
        'EU' AS SOURCE_REGION,
        _SOURCE AS SOURCE_SYSTEM
    FROM STAGING_EU.MARKETING_CAMPAIGNS

    UNION ALL

    -- US
    SELECT
        CAMPAIGN_ID,
        CAMPAIGN_NAME,
        CAMPAIGN_TYPE,
        CHANNEL,
        START_DATE,
        END_DATE,
        BUDGET_USD,
        TARGET_AUDIENCE,
        CAMPAIGN_STATUS,
        NULL AS IS_GDPR_COMPLIANT,
        CREATED_AT,
        created_at AS updated_at,
        'US' AS SOURCE_REGION,
        _SOURCE AS SOURCE_SYSTEM
    FROM STAGING_US.MARKETING_CAMPAIGNS
) AS SRC
ON ODS.CAMPAIGN_ID = SRC.CAMPAIGN_ID AND ODS.SOURCE_REGION = SRC.SOURCE_REGION

WHEN MATCHED THEN UPDATE SET
    CAMPAIGN_NAME = SRC.CAMPAIGN_NAME,
    CAMPAIGN_TYPE = SRC.CAMPAIGN_TYPE,
    CHANNEL = SRC.CHANNEL,
    START_DATE = SRC.START_DATE,
    END_DATE = SRC.END_DATE,
    BUDGET_USD = SRC.BUDGET_USD,
    TARGET_AUDIENCE = SRC.TARGET_AUDIENCE,
    CAMPAIGN_STATUS = SRC.CAMPAIGN_STATUS,
    IS_GDPR_COMPLIANT = SRC.IS_GDPR_COMPLIANT,
    CREATED_AT = SRC.CREATED_AT,
    UPDATED_AT = SRC.UPDATED_AT,
    SOURCE_SYSTEM = SRC.SOURCE_SYSTEM

WHEN NOT MATCHED THEN INSERT (
    CAMPAIGN_ID, CAMPAIGN_NAME, CAMPAIGN_TYPE, CHANNEL, START_DATE, END_DATE,
    BUDGET_USD, TARGET_AUDIENCE, CAMPAIGN_STATUS, IS_GDPR_COMPLIANT,
    CREATED_AT, UPDATED_AT, SOURCE_REGION, SOURCE_SYSTEM
) VALUES (
    SRC.CAMPAIGN_ID, SRC.CAMPAIGN_NAME, SRC.CAMPAIGN_TYPE, SRC.CHANNEL, SRC.START_DATE, SRC.END_DATE,
    SRC.BUDGET_USD, SRC.TARGET_AUDIENCE, SRC.CAMPAIGN_STATUS, SRC.IS_GDPR_COMPLIANT,
    SRC.CREATED_AT, SRC.UPDATED_AT, SRC.SOURCE_REGION, SRC.SOURCE_SYSTEM
);

    """
